services:
  backend:
    image: $IMAGE_NAME:$IMAGE_TAG
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - backend-network
    volumes:
      - ./logs:/app/logs
networks:
  backend-network:
    driver: bridge
