#!/bin/bash

echo IMAGE_NAME=$IMAGE_NAME > .env
echo IMAGE_TAG=$IMAGE_TAG >> .env

# Add variables here
echo PORT=$PORT >> .env
echo MONGO_URL=$MONGO_URL >> .env
echo ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET >> .env
echo REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET >> .env
echo FRONTEND_URL=$FRONTEND_URL >> .env
echo MOBILE_FRONTEND_URL=$MOBILE_FRONTEND_URL >> .env
echo TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID >> .env
echo TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN >> .env
echo TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER >> .env
echo MONGO_URL_CLUSTER=$MONGO_URL_CLUSTER >> .env

# Twilio credentials


# Twilio credentials 2
echo TWILIO_SMS_URL=$TWILIO_SMS_URL >> .env
echo TWILIO_VOICE_URL=$TWILIO_VOICE_URL >> .env
echo TWILIO_STATUS_CALLBACK=$TWILIO_STATUS_CALLBACK >> .env
 
# Nodemiler credentials
echo NODEMAILER_EMAIL=$NODEMAILER_EMAIL >> .env
echo NODEMAILER_EMAIL_PASSWORD=$NODEMAILER_EMAIL_PASSWORD >> .env

# Node environment
echo NODE_ENV=$NODE_ENV >> .env

# AWS credentials
echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> .env
echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> .env
echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> .env
echo S3_IMAGES_BUCKET_NAME=$S3_IMAGES_BUCKET_NAME >> .env

# Twilio callback
echo TWILIO_CALLBACK_URL=$TWILIO_CALLBACK_URL >> .env