#!/bin/bash

echo IMAGE_NAME=$IMAGE_NAME > .env
echo IMAGE_TAG=$IMAGE_TAG >> .env

# Add variables here
echo PORT=$PORT >> .env
echo MONGO_URL=$MONGO_URL >> .env
echo ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET >> .env
echo REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET >> .env
echo FRONTEND_URL=$FRONTEND_URL >> .env
echo TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID >> .env
echo TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN >> .env
echo TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER >> .env